[[language]]
name = "c-sharp"
scope = "source.cs"
injection-regex = "cs"
file-types = ["cs", "cshtml"]
indent = { tab-width = 4, unit = "    " }
# formatter = { command = "dotnet", args = ["format", "--include %{buffer_name}"] }
language-servers = ["csharp"]

[language-server.omnisharp]
command="/usr/bin/omnisharp"
args = ["-lsp"]

[language-server.csharp]
command="csharp-language-server"


[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rs|rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
shebangs = ["rust-script", "cargo"]
auto-format = true
language-servers = [ "rust-analyzer" ]
indent = { tab-width = 4, unit = "    " }
persistent-diagnostic-sources = ["rustc", "clippy"]


[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "livemd", "markdown", "mdx", "mkd", "mkdn", "mdwn", "mdown", "markdn", "mdtxt", "mdtext", "workbook", { glob = "PULLREQ_EDITMSG" }]
roots = [".marksman.toml"]
language-servers = [ "markdown-oxide" ]
indent = { tab-width = 2, unit = "  " }

[language-server.markdown-oxide]
command="/usr/bin/markdown-oxide"

[[language]]
name = "html"
scope = "text.html.basic"
injection-regex = "html"
file-types = ["html", "htm", "shtml", "xhtml", "xht", "jsp", "asp", "aspx", "jshtm", "volt", "rhtml", "cshtml"]
block-comment-tokens = { start = "<!--", end = "-->" }
language-servers = [ "vscode-html-language-server" ]
auto-format = false
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "tsx"
language-servers = [ "eslint", "emmet-ls", "typescript-language-server", "tailwindcss-ls", "gpt" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [ "eslint", "emmet-ls", "typescript-language-server", "tailwindcss-ls", "gpt" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true
